### PR TITLE
Implement cross-chain governance contracts on Reactive' Testnet

### PR DESCRIPTION
**Pull request by hhio618**
This pull request introduces the implementation of the Reactive Network Cross-Chain Governance system. 
Thank you for reviewing this pull request. Looking forward to your feedback.   
Related bounty: https://dorahacks.io/daobounty/456
Related issue: https://github.com/Reactive-Network/reactive-bounties/issues/4
## Contact information
Discord: hhio618#5800
Telegram: @hhio618
X: @hhio618

### CODE REVIEW

**Comment by Ivan-Ivanitskiy** [comment]
Hey @hhio618 !

Thank you very much for your application! It looks very good. The only thing I see missing is this:
"The participant MUST run this workflow on Sepolia and Reactive Testnets. The application MUST include the transaction hashes for every step of the workflow."
This is separate from deployment and implies the whole set up working, RSC interacting with the Descination contract based on the events on the Origin contract. Please add the description of the workflow with txs on the origin and destination chain. Or let me know where it is if I've somehow missed it.

Have a great day!

**Comment by hhio618** [comment]
Hey @Ivan-Ivanitskiy ,

Thank you for your feedback! I have updated my application to include the description of the workflow with the transaction hashes on both the origin and destination chains, as requested. Additionally, I have made improvements to my code.

Regards

**Comment by hhio618** [comment]
@Ivan-Ivanitskiy I tested all the functionalities and it's ready for another review!

**Comment by Ivan-Ivanitskiy** [comment]
Hello!

Unfortunately, the jury decided that your submission did not fulfill the application criteria. It does not have the Origin Governance contract, which is required in the bounty description. It emulates the Origin contract with ReGovEvents.sol. After a round of discussion me and other judges decided that it cannot really be called Cross-Chain Governance, for it does not allow voting on the origin chain - just owner-triggered events. 

We will be happy to see you in our upcoming events and try to win next time.

Thank you for your participation!

**Pull request closed without merging**
